// Code generated by "stringer -type=AlertType -trimprefix=AlertType"; DO NOT EDIT.

package alerts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertTypeNone-0]
	_ = x[AlertTypeMissiles-1]
	_ = x[AlertTypeRadiologicalEvent-2]
	_ = x[AlertTypeEarthQuake-3]
	_ = x[AlertTypeTsunami-4]
	_ = x[AlertTypeHostileAircraftIntrusion-5]
	_ = x[AlertTypeHazardousMaterials-6]
	_ = x[AlertTypeTerroristInfiltration-7]
	_ = x[AlertTypeMissilesDrill-11]
	_ = x[AlertTypeEarthQuakeDrill-12]
	_ = x[AlertTypeEnd-13]
	_ = x[AlertTypeGetReady-14]
	_ = x[AlertTypeHostileAircraftIntrusionDrill-15]
	_ = x[AlertTypeHazardousMaterialsDrill-16]
	_ = x[AlertTypeTerroristInfiltrationDrill-17]
	_ = x[AlertTypeUnknown - -1]
}

const (
	_AlertType_name_0 = "UnknownNoneMissilesRadiologicalEventEarthQuakeTsunamiHostileAircraftIntrusionHazardousMaterialsTerroristInfiltration"
	_AlertType_name_1 = "MissilesDrillEarthQuakeDrillEndGetReadyHostileAircraftIntrusionDrillHazardousMaterialsDrillTerroristInfiltrationDrill"
)

var (
	_AlertType_index_0 = [...]uint8{0, 7, 11, 19, 36, 46, 53, 77, 95, 116}
	_AlertType_index_1 = [...]uint8{0, 13, 28, 31, 39, 68, 91, 117}
)

func (i AlertType) String() string {
	switch {
	case -1 <= i && i <= 7:
		i -= -1
		return _AlertType_name_0[_AlertType_index_0[i]:_AlertType_index_0[i+1]]
	case 11 <= i && i <= 17:
		i -= 11
		return _AlertType_name_1[_AlertType_index_1[i]:_AlertType_index_1[i+1]]
	default:
		return "AlertType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
}
