// Code generated by "stringer -type=AlertType -trimprefix=AlertType"; DO NOT EDIT.

package alerts

import "strconv"

func _() {
	// An "invalid array index" compiler error signifies that the constant values have changed.
	// Re-run the stringer command to generate them again.
	var x [1]struct{}
	_ = x[AlertTypeNone-0]
	_ = x[AlertTypeMissileAlert-1]
	_ = x[AlertTypeUAV-2]
	_ = x[AlertTypeNonConventional-3]
	_ = x[AlertTypeWarning-4]
	_ = x[AlertTypeMemorialDay1-5]
	_ = x[AlertTypeMemorialDay2-6]
	_ = x[AlertTypeEarthquakeAlert1-7]
	_ = x[AlertTypeEarthquakeAlert2-8]
	_ = x[AlertTypeCBRNE-9]
	_ = x[AlertTypeTerrorAttack-10]
	_ = x[AlertTypeTsunami-11]
	_ = x[AlertTypeHazmat-12]
	_ = x[AlertTypeUpdate-13]
	_ = x[AlertTypeFlash-14]
	_ = x[AlertTypeMissileAlertDrill-15]
	_ = x[AlertTypeUAVDrill-16]
	_ = x[AlertTypeNonConventionalDrill-17]
	_ = x[AlertTypeWarningDrill-18]
	_ = x[AlertTypeMemorialDayDrill1-19]
	_ = x[AlertTypeMemorialDayDrill2-20]
	_ = x[AlertTypeEarthquakeDrill1-21]
	_ = x[AlertTypeEarthquakeDrill2-22]
	_ = x[AlertTypeCBRNEDrill-23]
	_ = x[AlertTypeTerrorAttackDrill-24]
	_ = x[AlertTypeTsunamiDrill-25]
	_ = x[AlertTypeHazmatDrill-26]
	_ = x[AlertTypeUpdateDrill-27]
	_ = x[AlertTypeFlashDrill-28]
	_ = x[AlertTypeUnknown - -1]
}

const _AlertType_name = "UnknownNoneMissileAlertUAVNonConventionalWarningMemorialDay1MemorialDay2EarthquakeAlert1EarthquakeAlert2CBRNETerrorAttackTsunamiHazmatUpdateFlashMissileAlertDrillUAVDrillNonConventionalDrillWarningDrillMemorialDayDrill1MemorialDayDrill2EarthquakeDrill1EarthquakeDrill2CBRNEDrillTerrorAttackDrillTsunamiDrillHazmatDrillUpdateDrillFlashDrill"

var _AlertType_index = [...]uint16{0, 7, 11, 23, 26, 41, 48, 60, 72, 88, 104, 109, 121, 128, 134, 140, 145, 162, 170, 190, 202, 219, 236, 252, 268, 278, 295, 307, 318, 329, 339}

func (i AlertType) String() string {
	idx := int(i) - -1
	if i < -1 || idx >= len(_AlertType_index)-1 {
		return "AlertType(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _AlertType_name[_AlertType_index[idx]:_AlertType_index[idx+1]]
}
